# Generated by Django 4.2.6 on 2023-11-07 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_created_at_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("315d4a93-989f-4dd3-b4ee-2c860e6451a5"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
