# Generated by Django 4.2.6 on 2023-12-01 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.CreateModel(
            name="SiteDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Clothing store", max_length=200)),
                ("desc", models.TextField(null=True)),
                (
                    "fb",
                    models.URLField(
                        default="https://www.facebook.com/", verbose_name="Facebook"
                    ),
                ),
                (
                    "tw",
                    models.URLField(
                        default="https://twitter.com/", verbose_name="Twitter"
                    ),
                ),
                (
                    "ig",
                    models.URLField(
                        default="https://www.instagram.com/", verbose_name="Instagram"
                    ),
                ),
                (
                    "ln",
                    models.URLField(
                        default="https://www.linkedin.com/", verbose_name="LinkedIn"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Detail",
                "verbose_name_plural": "Site Details",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Co-Founder", "Co-Founder"),
                            ("Product Expert", "Product Expert"),
                            ("Chief Marketing", "Chief Marketing"),
                            ("Product Specialist", "Product Specialist"),
                            ("Product Photographer", "Product Photographer"),
                            ("General Manager", "General Manager"),
                        ],
                        max_length=200,
                    ),
                ),
                ("desc", models.TextField(null=True)),
                ("avatar", models.ImageField(null=True, upload_to="team/")),
                (
                    "fb",
                    models.URLField(
                        default="https://www.facebook.com/", verbose_name="Facebook"
                    ),
                ),
                (
                    "tw",
                    models.URLField(
                        default="https://twitter.com/", verbose_name="Twitter"
                    ),
                ),
                (
                    "ig",
                    models.URLField(
                        default="https://www.instagram.com/", verbose_name="Instagram"
                    ),
                ),
                (
                    "ln",
                    models.URLField(
                        default="https://www.linkedin.com/", verbose_name="LinkedIn"
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
    ]
