# Generated by Django 4.2.6 on 2023-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedetail",
            name="working_hours",
            field=models.CharField(default="Mon - Fri: 8AM - 10PM", max_length=200),
        ),
    ]
