# Generated by Django 4.2.6 on 2023-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_sitedetail_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedetail",
            name="email",
            field=models.EmailField(default="email@gmail.com", max_length=254),
        ),
        migrations.AddConstraint(
            model_name="sitedetail",
            constraint=models.CheckConstraint(
                check=models.Q(("id__isnull", False), _negated=True),
                name="unique_site_detail_id",
            ),
        ),
    ]
