# Generated by Django 4.2.6 on 2023-12-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0004_remove_sitedetail_unique_site_detail_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sitedetail",
            options={},
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={},
        ),
        migrations.RemoveField(
            model_name="message",
            name="message",
        ),
        migrations.RemoveField(
            model_name="sitedetail",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(default="@email.com"),
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="address",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="maps_url",
            field=models.URLField(
                default="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
            ),
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="work_hours",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="fb",
            field=models.URLField(
                default="https://www.facebook.com", verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="ln",
            field=models.URLField(
                default="https://www.linkedin.com/", verbose_name="Linkedin"
            ),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="name",
            field=models.CharField(default="Clothing Store", max_length=200),
        ),
        migrations.AlterField(
            model_name="sitedetail",
            name="tw",
            field=models.URLField(
                default="https://www.twitter.com/", verbose_name="Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="avatar",
            field=models.ImageField(default="True", upload_to="team/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="desc",
            field=models.CharField(default="True", max_length=300),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="fb",
            field=models.URLField(
                default="https://www.facebook.com", verbose_name="Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="ln",
            field=models.URLField(
                default="https://www.linkedin.com/", verbose_name="Linkedin"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("CO-Founder", "CO-Founder"),
                    ("Product Expert", "Product Expert"),
                    ("Chief Marketing", "Chief Marketing"),
                    ("Product Specialist", "Product Specialist"),
                    ("Product Photographer", "Product Photographer"),
                    ("General Manager", "General Manager"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="tw",
            field=models.URLField(
                default="https://www.twitter.com/", verbose_name="Twitter"
            ),
        ),
    ]
