# Generated by Django 4.2.6 on 2023-12-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0005_alter_message_options_alter_sitedetail_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="avatar",
            field=models.ImageField(upload_to="team/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="desc",
            field=models.CharField(max_length=300),
        ),
    ]
