# Generated by Django 4.2.6 on 2023-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0006_alter_message_text_alter_teammember_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedetail",
            name="email",
            field=models.EmailField(default="clothingstore@gmail.com", max_length=254),
        ),
    ]
