# Generated by Django 4.2.6 on 2023-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0007_alter_sitedetail_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitedetail",
            name="work_hours",
        ),
        migrations.AddField(
            model_name="sitedetail",
            name="working_hours",
            field=models.CharField(default="Mon - Fri: 8AM - 10PM", max_length=200),
        ),
    ]
