# Generated by Django 4.2.6 on 2023-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0008_remove_sitedetail_work_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedetail",
            name="maps_url",
            field=models.URLField(
                default="https://www.google.com/maps?q=10+Broad+Street,+Lagos,+Nigeria&z=13&ie=UTF8&iwloc=&output=embed"
            ),
        ),
    ]
