# Generated by Django 4.2.6 on 2023-11-07 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="update_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="update_time",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="create_time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="update_time",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3416618-eb67-4381-b09d-7c2ffc34451c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3416618-eb67-4381-b09d-7c2ffc34451c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a3416618-eb67-4381-b09d-7c2ffc34451c"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
